# --------------------------------
# 1. 环境变量配置（复用现有ConfigMap/Secret）
# --------------------------------
apiVersion: v1
kind: ConfigMap
metadata:
  name: d2vm-env-config
  namespace: haios
data:
  # 服务发现：通过K8s DNS解析Service名称
  MYSQL_HOST: "mysql.haios.svc.cluster.local"  # 标准DNS格式[3](@ref)
  MYSQL_PORT: "3306"
  MYSQL_DATABASE: "haios_db"
  MYSQL_USER: "haios_d2vm"
  REDIS_HOST: "redis-master.haios.svc.cluster.local" 
  REDIS_PORT: "6379"
  # 非敏感配置
  DJANGO_SETTINGS_MODULE: "myproject.settings"
  GUNICORN_WORKERS: "4" 

---
# --------------------------------
# 2. 部署应用
# --------------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: d2vm-app
  namespace: haios
spec:
  replicas: 1
  selector:
    matchLabels:
      app: d2vm
  template:
    metadata:
      labels:
        app: d2vm
    spec:
      containers:
      - name: d2vm-container
        image: haios/d2vm:beta-0.1
        imagePullPolicy: Never  # 关键修改：禁用远程拉取[1,4](@ref)
        ports:
        - containerPort: 9000
        # 外挂母机代码仓库, 方便开发调试，因为容器内部很简陋，没有git等工具
        # volumeMounts:
        # - name: host-data-volume
        #   mountPath: /opt/D2VM
        # 动态注入环境变量
        env:
          # 从ConfigMap读取非敏感配置
          - name: MYSQL_HOST
            valueFrom:
              configMapKeyRef:
                name: d2vm-env-config
                key: MYSQL_HOST
          - name: MYSQL_PORT
            valueFrom:
              configMapKeyRef:
                name: d2vm-env-config
                key: MYSQL_PORT
          - name: MYSQL_DATABASE
            valueFrom:
              configMapKeyRef:
                name: d2vm-env-config
                key: MYSQL_DATABASE
          - name: MYSQL_USER
            valueFrom:
              configMapKeyRef:
                name: d2vm-env-config
                key: MYSQL_USER
          - name: REDIS_HOST
            valueFrom:
              configMapKeyRef:
                name: d2vm-env-config
                key: REDIS_HOST
          - name: REDIS_PORT
            valueFrom:
              configMapKeyRef:
                name: d2vm-env-config
                key: REDIS_PORT
          # 从Secret读取敏感凭据
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql
                key: mysql-password
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: redis  # 复用Redis Secret
                key: redis-password
        # 健康检查（需Django实现/health端点）
        # livenessProbe:
        #   httpGet:
        #     path: /health/
        #     port: 9000
        #   initialDelaySeconds: 30
        #   periodSeconds: 10
        # readinessProbe:
        #   httpGet:
        #     path: /health/
        #     port: 9000
        #   initialDelaySeconds: 15
        #   periodSeconds: 5
      volumes:
      - name: host-data-volume
        hostPath:
          path: /data/haios/deployment/D2VM
          type: DirectoryOrCreate

---
# --------------------------------
# 3. 服务暴露（NodePort）
# --------------------------------
apiVersion: v1
kind: Service
metadata:
  name: d2vm-service
  namespace: haios
spec:
  selector:
    app: d2vm
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
      nodePort: 30080
  type: NodePort
