# --------------------------------
# 1. 环境变量配置（复用现有ConfigMap/Secret）
# --------------------------------
apiVersion: v1
kind: ConfigMap
metadata:
  name: d2vm-env-config
  namespace: haios
data:
  # 服务发现：通过K8s DNS解析Service名称
  MYSQL_HOST: "mysql.haios.svc.cluster.local"  # 标准DNS格式[3](@ref)
  MYSQL_PORT: "3306"
  REDIS_HOST: "redis-master.haios.svc.cluster.local" 
  REDIS_PORT: "6379"
  # 非敏感配置
  DJANGO_SETTINGS_MODULE: "myproject.settings"
  GUNICORN_WORKERS: "4" 

---
# --------------------------------
# 2. 部署应用
# --------------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: d2vm-app
  namespace: haios
spec:
  replicas: 2
  selector:
    matchLabels:
      app: d2vm
  template:
    metadata:
      labels:
        app: d2vm
    spec:
      containers:
      - name: d2vm-container
        image: haios/d2vm:alpha
        ports:
        - containerPort: 9000
        # 动态注入环境变量
        env:
          # 从ConfigMap读取非敏感配置
          - name: MYSQL_HOST
            valueFrom:
              configMapKeyRef:
                name: d2vm-env-config
                key: MYSQL_HOST
          - name: MYSQL_PORT
            valueFrom:
              configMapKeyRef:
                name: d2vm-env-config
                key: MYSQL_PORT
          # 从Secret读取敏感凭据
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                name: mysql  # 使用现有Secret[1](@ref)
                key: mysql-root-user  # 根据Secret实际字段调整
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql
                key: mysql-root-password
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: redis  # 复用Redis Secret
                key: redis-password
        # 健康检查（需Django实现/health端点）
        livenessProbe:
          httpGet:
            path: /health/
            port: 9000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health/
            port: 9000
          initialDelaySeconds: 15
          periodSeconds: 5

---
# --------------------------------
# 3. 服务暴露（NodePort）
# --------------------------------
apiVersion: v1
kind: Service
metadata:
  name: d2vm-service
  namespace: haios
spec:
  selector:
    app: d2vm
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
      nodePort: 30090  
  type: NodePort
